services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    env_file:
      - .env.docker
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: task-api-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_api
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: